stages:
  - build

build:
  stage: build
  script:
    - cd sepia2-grpc
    - nix --extra-experimental-features "nix-command flakes" develop --impure ..# -c cargo build --release --target x86_64-pc-windows-gnu --bin sepia2-grpc-server
    #- cargo build --release --target x86_64-unknown-linux-gnu --lib
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/sepia2-grpc-server.exe
      #- target/release/libclient/so
