[package]
name = "pq-driver-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt = "0.1.0"
log = "0.4.25"

[build-dependencies]
bindgen = "0.71.0"
